GET http://localhost:8080/api/products/1

###

GET http://localhost:8080/api/products

###

GET http://localhost:8080/api/products?Coruscant

###

OPTIONS http://localhost:8080/api/products

###

POST http://localhost:8080/api/products
Content-Type: application/vnd-products+json

{
  "name": "DL-44 heavy blaster pistol",
  "price": 12,
  "orders": []
}

###

POST http://localhost:8080/api/products
Content-Type: application/vnd-products+json

{
  "name": "X-Wing",
  "price": 31589,
  "orders": []
}

###

POST http://localhost:8080/api/products
Content-Type: application/vnd-products+json

{
  "name": "AAT",
  "price": 46,
  "orders": []
}

###

POST http://localhost:8080/api/products
Content-Type: application/vnd-products+json

{
  "name": "Death Star",
  "price": 544932187,
  "orders": []
}

###

DELETE http://localhost:8080/api/products/1

###