GET http://localhost:8080/api/products/1
Content-Type: application/vnd-products+json

###

GET http://localhost:8080/api/products
Content-Type: application/vnd-products+json

###

GET http://localhost:8080/api/products?Coruscant
Content-Type: application/vnd-products+json

###

OPTIONS http://localhost:8080/api/products
Content-Type: application/vnd-products+json

###

POST http://localhost:8080/api/products
Content-Type: application/vnd-products+json

{
  "name": "DL-44 heavy blaster pistol",
  "price": 12,
  "ordersIds": []
}

###

POST http://localhost:8080/api/products
Content-Type: application/vnd-products+json

{
  "name": "X-Wing",
  "price": 31589,
  "ordersIds": []
}

###

POST http://localhost:8080/api/products
Content-Type: application/vnd-products+json

{
  "name": "AAT",
  "price": 46,
  "ordersIds": []
}

###

POST http://localhost:8080/api/products
Content-Type: application/vnd-products+json

{
  "name": "Death Star",
  "price": 544932187,
  "ordersIds": []
}

###

DELETE http://localhost:8080/api/products/43
Content-Type: application/vnd-products+json

###

DELETE http://localhost:8080/api/products/41?customerId=30
Content-Type: application/vnd-products+json

###

GET http://localhost:8080/api/products/41
Content-Type: application/vnd-products+json

###